### PR TITLE
Add parameters gradesAverages

### PR DESCRIPTION
**Pull request by ioull**

### CODE REVIEW

**Comment by ioull** [comment]
Add parameters gradesAverages
Split grade and out of in order to display only what we want ... but keep compatibility with student_grade

**Comment by bdbogjoe** [comment]
@vingerha  possible to merge this ?

**Comment by vingerha** [comment]
Guess so, I am however still awaiting a new release of pronotepy to fix MY issue... then I will aim for a new release on this one

**Comment by vingerha** [comment]
I got word from PronotePy (bapt5), he will try to integrate his work in the school holidays. As I want both the new coverage for 'punishment' as well as his solution for agora06, I cannot progress till then.

**Pull request merged**
